version: '3.8'

services:
  mysql:
    container_name: auth-service-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
